### ISSUE TITLE
Error when requesting plugin (Error code 400) when trying to load a big playlist

### ISSUE THREAD

**Issue by StaringLongingly** [soundcrowd/soundcrowd-plugin-spotify#1]
i tried to load my playlists and my bigger ones refuse to, while the smaller ones work just fine

**Comment by 0xf4b1** [comment]
Hey, thanks for the report. This issue should be fixed in the new [0.4.1 release](https://github.com/soundcrowd/soundcrowd-plugin-spotify/releases/tag/v0.4.1) of the plugin.
