### ISSUE TITLE
Banned my account

### ISSUE THREAD

**Issue by jooapa** [soundcrowd/soundcrowd-plugin-spotify#2]
Haven't have any major problems, but I guess spotify didn"t like me so they banned or deactivated my account. After making another account, they banned that one too. 

So I wouldn't recommend using rn

**Comment by 0xf4b1** [comment]
I also had to reset my password and have my account working again. But with the plugin and the libspotify in general, I can no longer login and get a BadCredentials exception :( Looks like the library needs an update because spotify changed something.
